language: python

# Supported Python versions
python:
  # CPython versions
  - "3.6"
  - "3.7"
  - "3.8"
  # PyPy versions
  - "pypy3"

# Dependency installation
install:
  - pip install .
  - pip install .[test]
  - pip install .[backend-networkx]

script: pytest

jobs:
  include:
    - stage: integration
      name: Integration tests
      python: "3.8"
      script: .travis/integration-tests.sh

# Notifications
#notifications:
#  email:
#    recipients:
#    on_success: change
#    on_failure: change

# Git-related settings
git:
  depth: 3
branches:
  only:
    - master
    - dev
    - /^deploy.*$/