language: python

# Supported Python versions
python:
  # CPython versions
  - "3.6"
  - "3.7"
  - "3.8"
  # PyPy versions
  - "pypy3"

# Dependency installation
install:
  # Install requirements
  - pip install .
  # Install plugins
  - pip install .[test]
  - pip install .[backend-networkx]

script: pytest

jobs:
  include:
    - stage: integration
      name: Integration tests
      python: "3.6"
      script: .travis/integration-tests.sh
    - stage: integration
      name: Integration tests
      python: "3.8"
      script: .travis/integration-tests.sh
    - stage: integration
      name: Integration tests
      python: "pypy3"
      script: .travis/integration-tests.sh

# Git-related settings
git:
  depth: 3
branches:
  only:
    - master
    - dev
    - /^deploy.*$/